### ISSUE TITLE
`File > Save Image` doesn't work on rviz

### ISSUE THREAD

**Issue by IamPhytan** [norlab-ulaval/percep3d_exercises#2]
rviz lags and gives an error with the `Save Image` function in the provided virtual machine :

```
this function is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
Gtk-Message: 13:52:16.864: GtkDialog mapped without a transient parent. This is discouraged.
```

Looks like the legacy screenshot function of Ubuntu seems like the best option right now

**Comment by pomerlef** [comment]
Indeed, we should change instructions before the next release.
